# Generated by Django 4.1.4 on 2023-01-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_options_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_on',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
