# Generated by Django 4.1.4 on 2023-01-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, default='1983-09-14', null=True, verbose_name='Дата рождения'),
        ),
    ]
