# Generated by Django 4.1.4 on 2023-02-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(default='', help_text='Ссылка на фото товара'),
        ),
    ]
